### ISSUE TITLE
How to set default month selection

### ISSUE THREAD

**Issue by Shyam11Moorthy** [kleinrein/vue-month-picker#10]
We have used MonthPickerInput.  Default month and  year values are not displayed by default even we used default month and default year property for default selection. 

Is possible to display month and year values by default.

**Comment by kleinrein** [comment]
I will take a look at it later tonight. Thanks.

**Comment by kleinrein** [comment]
Could you test the new version v.1.2.4? If you are still having issues, please paste the code here.

**Comment by nextmat** [comment]
FWIW I can confirm that this works with `MonthPicker` in v1.2.4
