### ISSUE TITLE
$emit on month-picker-input

### ISSUE THREAD

**Issue by dlenskyi** [kleinrein/vue-month-picker#37]
Why you don't have events on month-picker-input?

**Comment by kleinrein** [comment]
You can use @change event to listen to any changed value in the month-picker, or is it something else you are after?

**Comment by dlenskyi** [comment]
@kleinrein @change event can be used only for <month-picker> component, but not for component <month-picker-input>, Thats why I need to you input fields and append to this field month-picker components, but it would be great to use just month-picker-input :))

**Comment by kleinrein** [comment]
Fixed in v.1.3.1
