### ISSUE TITLE
Month picker popup is cropped

### ISSUE THREAD

**Issue by nimbusparis** [kleinrein/vue-month-picker#47]
Hello,
When the component is too close from the right border of the view, the month picker popup is cropped. It should be aligned with the view border to be correctly displayed. 
![image](https://user-images.githubusercontent.com/10380146/101607776-3f872100-3a05-11eb-88a0-925359107946.png)

**Comment by kleinrein** [comment]
Hello.

I'm not sure I understand. Is the issue that it scales down?

**Comment by nimbusparis** [comment]
The black bar on the right is the edge of the browser. And if you try to size up the browser window, the popup is still cropped.

**Comment by kleinrein** [comment]
I see. It looks like you need to look at the container of the month picker or you can adjust the month picker by setting `left: -2rem;` or `margin-right: 2rem;`. The month picker itself has a fixed width of 400px and the position is relative.
