### ISSUE TITLE
How to use without a bundler?

### ISSUE THREAD

**Issue by dennishilmar** [kleinrein/vue-month-picker#48]
I'm not using bundlers, but I'd still like to use this module.

Maybe via unkpg, jsdelivr or just a pre-compiled download link?

Is that possible?

I can see a dist folder in jsdelivr, but not really sure if I can use it..
https://cdn.jsdelivr.net/npm/vue-month-picker@1.4.0/dist/

**Comment by kleinrein** [comment]
Hmm, I'm not sure.. I couldn't get it to work, maybe I need to do something on the build phase. But could you try these?
CSS: https://unpkg.com/vue-month-picker@1.4.0/dist/assets/css/index.1e112929.chunk.css
JS: https://unpkg.com/vue-month-picker@1.4.0/dist/assets/js/index.1e112929.chunk.js

**Comment by dennishilmar** [comment]
I cannot import it, but I can add it via <script> :)

It just needs to either add its components to Vue or leave a global define I can use.

fx Vue.component('month-picker', window.VueMonthPicker)

**Comment by ngekoding** [comment]
Any solution for this?

**Comment by kleinrein** [comment]
@ngekoding I haven't had the time to look at it yet. Did you see @dennishilmar message?
