### ISSUE TITLE
Prop for input placeholder

### ISSUE THREAD

**Issue by SkyHolder** [kleinrein/vue-month-picker#50]
I try pass placeholder proprty to component, but it appear as attribute of `month-picker-input-container`

**Comment by kleinrein** [comment]
I'm sorry for getting back to you so late. Did you manage to solve it? I'm not sure I follow. Can you provide an example?

**Comment by SkyHolder** [comment]
[https://codesandbox.io/s/tender-lederberg-enos3?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/tender-lederberg-enos3?fontsize=14&hidenavigation=1&theme=dark)

i'll try show some placeholder on input, make simple example

**Comment by Oshaine** [comment]
having the same issue, cant pass input placeholder prop to it

**Comment by kleinrein** [comment]
Fixed in v1.5.0. Closing for now. Please open again if issue still occur.
